[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/_energy_track/E2_Multivariate_Demand_RNN.ipynb)

# Multivariate RNN: Electricity Demand
--------------------------------------------------
**Dr. Dave Wanik - University of Connecticut**

Drop the lag columns. Hand the RNN the raw multivariate sequence as a **3-D tensor** `(samples, look-back, features)` - weather and clock on the left, **demand as the last column** - and let it decide what to remember. SimpleRNN first, then the one-word LSTM swap, then a stacked model with `return_sequences=True`, always scored against the dumb baselines. A classification head (peak hour or not?) closes the notebook so you see both output types on one dataset.

*Energy-track version of the occupancy RNN notebook.*

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 9B — Multivariate RNN Pt 1: split_sequences, column order, the 3-D tensor
- Multivariate differs from univariate only in prep: covariates on the left, target as the LAST column - and the target's own history stays in X. split_sequences takes y from the right.
- Look-back 24 -> (8736, 24, 8) train tensor. Walk the shape: samples, look-back, features. Inherit n_steps/n_features from the shape.
- SimpleRNN(30) with a LINEAR head (regression, MW) - params (8+30)*30+30 = 1,170 plus 31 for the head.
- Scale on train only; a separate scaler for the target so you can inverse_transform back to megawatts.
- Read the MAE against persistence (129) and seasonal naive (227): SimpleRNN ~48 MW, because the target's own past is in the window. That's the whole point of the column-order slide.
-->


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, classification_report, confusion_matrix
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, SimpleRNN, LSTM, GRU, Bidirectional, Conv1D, MaxPooling1D, Flatten
from keras.callbacks import EarlyStopping
import keras
keras.utils.set_random_seed(5509)   # reproducibility: same numbers every run (CPU exact; a GPU may drift a little)

## Read, sort, split

In [2]:
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/main/OPIM5509_Module4_Files/data/BDL_cleanweather_energy.csv"
df = pd.read_csv(url, parse_dates=["Datetime"])
print("in date order as delivered?", df["Datetime"].is_monotonic_increasing)      # it is NOT - always check
df = df.sort_values("Datetime").set_index("Datetime").ffill()

# two years is plenty for the lecture: train on 2018, test on 2019 - chronological, never shuffled
data  = df.loc["2018-01-01":"2019-12-31", ["BDL_tmpf", "BDL_dwpf", "BDL_relh", "Demand"]].copy()
data["hour_sin"] = np.sin(2*np.pi*data.index.hour/24); data["hour_cos"] = np.cos(2*np.pi*data.index.hour/24)
data["dow_sin"]  = np.sin(2*np.pi*data.index.dayofweek/7); data["dow_cos"] = np.cos(2*np.pi*data.index.dayofweek/7)
data = data[["BDL_tmpf", "BDL_dwpf", "BDL_relh", "hour_sin", "hour_cos", "dow_sin", "dow_cos", "Demand"]]   # Demand LAST
train, test = data.loc[:"2018-12-31"], data.loc["2019-01-01":]
print("train:", train.shape, "| test:", test.shape)
data.head()

in date order as delivered? False
train: (8760, 8) | test: (8760, 8)


,BDL_tmpf,BDL_dwpf,BDL_relh,hour_sin,hour_cos,dow_sin,dow_cos,Demand
Datetime,,,,,,,,
2018-01-01 00:00:00,1.9,0.0,56.85,0.000000,1.000000,0.0,1.0,3867.09
2018-01-01 01:00:00,0.0,0.0,62.12,0.258819,0.965926,0.0,1.0,3749.96
2018-01-01 02:00:00,0.0,0.0,61.38,0.500000,0.866025,0.0,1.0,3673.50
2018-01-01 03:00:00,0.0,0.0,71.11,0.707107,0.707107,0.0,1.0,3646.25
2018-01-01 04:00:00,0.0,0.0,64.21,0.866025,0.500000,0.0,1.0,3660.86


## Baselines

In [3]:
y = test["Demand"]
baselines = pd.Series({
    "mean-only":                       mean_absolute_error(y, np.full(len(y), train["Demand"].mean())),
    "seasonal naive (same hour yday)": mean_absolute_error(y.iloc[24:], y.shift(24).iloc[24:]),
    "persistence (last hour)":         mean_absolute_error(y.iloc[1:],  y.shift(1).iloc[1:]),
}, name="test MAE (MW)").round(1)
baselines

mean-only                          563.3
seasonal naive (same hour yday)    227.1
persistence (last hour)            129.0
Name: test MAE (MW), dtype: float64

## Prep: `split_sequences` and the 3-D tensor

Scale on train only. `split_sequences` takes the inputs from **every** column - demand's own past included - and the target from the last column at the **next** step.

In [4]:
def split_sequences(seqs, n_steps):
    X, y = [], []
    for i in range(len(seqs) - n_steps):
        X.append(seqs[i:i+n_steps, :]); y.append(seqs[i+n_steps, -1])   # inputs = EVERY column (demand's own past included); target = last col, NEXT step
    return np.array(X), np.array(y)

n_steps = 24
sc   = MinMaxScaler().fit(train)               # fit on TRAIN only
sc_y = MinMaxScaler().fit(train[["Demand"]])   # a separate scaler for the target so we can get MW back
tr_s, te_s = sc.transform(train), sc.transform(test)
X_train, y_train = split_sequences(tr_s, n_steps)
X_test,  y_test  = split_sequences(te_s, n_steps)
n_features = X_train.shape[2]
y_true = sc_y.inverse_transform(y_test.reshape(-1, 1)).ravel()   # test target in MW
print("train tensor:", X_train.shape, "-> (samples, look-back, features) | test:", X_test.shape)

train tensor: (8736, 24, 8) -> (samples, look-back, features) | test: (8736, 24, 8)


## SimpleRNN with a linear head

In [5]:
es = EarlyStopping(monitor="val_loss", patience=8, restore_best_weights=True, verbose=1)

rnn = Sequential([SimpleRNN(30, input_shape=(n_steps, n_features)), Dense(1)])   # linear output: we predict megawatts
rnn.compile(optimizer="adam", loss="mse", metrics=["mae"])
rnn.summary()
hist = rnn.fit(X_train, y_train, epochs=50, batch_size=64, validation_split=0.2, callbacks=[es], verbose=1)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,170 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,201 (4.69 KB)

 Trainable params: 1,201 (4.69 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 2:58 2s/step - loss: 0.5564 - mae: 0.7191

 16/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1133 - mae: 0.2661 

 33/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0706 - mae: 0.1990

 48/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0551 - mae: 0.1721

 63/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0458 - mae: 0.1553

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0395 - mae: 0.1427

 93/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0349 - mae: 0.1331

108/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0314 - mae: 0.1254

110/110 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 0.0311 - mae: 0.1248 - val_loss: 0.0082 - val_mae: 0.0746


Epoch 2/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - loss: 0.0089 - mae: 0.0786

 12/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0085 - mae: 0.0711 

 23/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0081 - mae: 0.0701

 34/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0078 - mae: 0.0690

 45/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0076 - mae: 0.0678

 55/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0075 - mae: 0.0675

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0072 - mae: 0.0661

 76/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0070 - mae: 0.0652

 86/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0068 - mae: 0.0644

 97/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0066 - mae: 0.0636

109/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0064 - mae: 0.0626

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0064 - mae: 0.0625 - val_loss: 0.0042 - val_mae: 0.0531


Epoch 3/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 0.0046 - mae: 0.0561

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0048 - mae: 0.0525 

 28/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0045 - mae: 0.0517

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0045 - mae: 0.0517

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0044 - mae: 0.0514

 64/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0043 - mae: 0.0506

 77/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0041 - mae: 0.0498

 91/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0040 - mae: 0.0493

104/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0039 - mae: 0.0486

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0039 - mae: 0.0484 - val_loss: 0.0027 - val_mae: 0.0420


Epoch 4/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 1:12 665ms/step - loss: 0.0029 - mae: 0.0446

  8/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0036 - mae: 0.0433    

 15/110 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0032 - mae: 0.0425

 19/110 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0031 - mae: 0.0421

 23/110 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0031 - mae: 0.0422

 28/110 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0031 - mae: 0.0420

 33/110 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0030 - mae: 0.0421

 37/110 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0031 - mae: 0.0424

 45/110 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0031 - mae: 0.0422

 51/110 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0030 - mae: 0.0422

 57/110 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0030 - mae: 0.0422

 67/110 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0029 - mae: 0.0416 

 74/110 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0029 - mae: 0.0413

 82/110 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0029 - mae: 0.0411

 93/110 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0028 - mae: 0.0409

102/110 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0028 - mae: 0.0404

110/110 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0027 - mae: 0.0402 - val_loss: 0.0020 - val_mae: 0.0354


Epoch 5/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 12s 115ms/step - loss: 0.0020 - mae: 0.0377

  7/110 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0028 - mae: 0.0378   

 11/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0026 - mae: 0.0367

 16/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0024 - mae: 0.0365

 24/110 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0362 

 34/110 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0360

 43/110 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0365

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0023 - mae: 0.0363

 60/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0023 - mae: 0.0361

 67/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0359

 77/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0356

 86/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0355

 92/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0021 - mae: 0.0354

102/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0021 - mae: 0.0351

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0021 - mae: 0.0350 - val_loss: 0.0016 - val_mae: 0.0312


Epoch 6/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - loss: 0.0015 - mae: 0.0332

 11/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0020 - mae: 0.0327 

 22/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0018 - mae: 0.0322

 34/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0018 - mae: 0.0319

 45/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0019 - mae: 0.0323

 58/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0018 - mae: 0.0322

 72/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0018 - mae: 0.0318

 88/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0017 - mae: 0.0316

105/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0017 - mae: 0.0313

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0017 - mae: 0.0313 - val_loss: 0.0013 - val_mae: 0.0280


Epoch 7/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 12s 117ms/step - loss: 0.0012 - mae: 0.0293

 11/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0017 - mae: 0.0297   

 19/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0015 - mae: 0.0291

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0015 - mae: 0.0291

 36/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0016 - mae: 0.0291

 47/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0016 - mae: 0.0295

 57/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0015 - mae: 0.0293

 68/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0015 - mae: 0.0290

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0014 - mae: 0.0288

 91/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0014 - mae: 0.0288

105/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0014 - mae: 0.0285

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0014 - mae: 0.0285 - val_loss: 0.0011 - val_mae: 0.0256


Epoch 8/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 9.7036e-04 - mae: 0.0261

 17/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0013 - mae: 0.0266     

 34/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0013 - mae: 0.0267

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0013 - mae: 0.0271

 70/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0012 - mae: 0.0266

 88/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0012 - mae: 0.0266

106/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0012 - mae: 0.0264

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0012 - mae: 0.0264 - val_loss: 9.5864e-04 - val_mae: 0.0240


Epoch 9/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - loss: 8.2678e-04 - mae: 0.0238

 15/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0011 - mae: 0.0246     

 29/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0011 - mae: 0.0250

 45/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0011 - mae: 0.0252

 60/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0011 - mae: 0.0251

 77/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0011 - mae: 0.0247

 94/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0011 - mae: 0.0249

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0010 - mae: 0.0247 - val_loss: 8.5831e-04 - val_mae: 0.0228


Epoch 10/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 7.2906e-04 - mae: 0.0221

 18/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.7512e-04 - mae: 0.0233 

 32/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.6289e-04 - mae: 0.0233

 46/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0010 - mae: 0.0238    

 58/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.6803e-04 - mae: 0.0236

 69/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.5220e-04 - mae: 0.0234

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.3773e-04 - mae: 0.0233

 87/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.4031e-04 - mae: 0.0234

 96/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.4008e-04 - mae: 0.0233

108/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.2621e-04 - mae: 0.0232

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2509e-04 - mae: 0.0232 - val_loss: 7.7826e-04 - val_mae: 0.0218


Epoch 11/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - loss: 6.6125e-04 - mae: 0.0209

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6086e-04 - mae: 0.0218 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6052e-04 - mae: 0.0222

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.9782e-04 - mae: 0.0225

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7075e-04 - mae: 0.0224

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5430e-04 - mae: 0.0222

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.3770e-04 - mae: 0.0220

 90/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.4381e-04 - mae: 0.0222

100/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.3819e-04 - mae: 0.0221

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2948e-04 - mae: 0.0221 - val_loss: 7.1508e-04 - val_mae: 0.0210


Epoch 12/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - loss: 6.1260e-04 - mae: 0.0199

 12/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1594e-04 - mae: 0.0213 

 22/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8304e-04 - mae: 0.0211

 34/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7781e-04 - mae: 0.0211

 47/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0853e-04 - mae: 0.0215

 59/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7861e-04 - mae: 0.0213

 68/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6972e-04 - mae: 0.0211

 80/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6102e-04 - mae: 0.0211

 92/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6550e-04 - mae: 0.0212

104/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5606e-04 - mae: 0.0211

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5169e-04 - mae: 0.0210 - val_loss: 6.6485e-04 - val_mae: 0.0203


Epoch 13/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - loss: 5.7461e-04 - mae: 0.0191

 15/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1091e-04 - mae: 0.0200 

 28/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1486e-04 - mae: 0.0203

 41/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3770e-04 - mae: 0.0205

 49/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3016e-04 - mae: 0.0206

 60/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1136e-04 - mae: 0.0204

 73/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9725e-04 - mae: 0.0202

 86/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9481e-04 - mae: 0.0202

 99/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9436e-04 - mae: 0.0202

110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8632e-04 - mae: 0.0201

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.8632e-04 - mae: 0.0201 - val_loss: 6.2177e-04 - val_mae: 0.0197


Epoch 14/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - loss: 5.3813e-04 - mae: 0.0183

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5590e-04 - mae: 0.0192 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5707e-04 - mae: 0.0196

 37/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7026e-04 - mae: 0.0195

 47/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.7357e-04 - mae: 0.0197

 59/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5096e-04 - mae: 0.0196

 71/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3840e-04 - mae: 0.0193

 83/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3696e-04 - mae: 0.0194

 95/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4270e-04 - mae: 0.0195

106/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3347e-04 - mae: 0.0194

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.3024e-04 - mae: 0.0193 - val_loss: 5.8034e-04 - val_mae: 0.0191


Epoch 15/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - loss: 4.9567e-04 - mae: 0.0174

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0325e-04 - mae: 0.0184 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0511e-04 - mae: 0.0188

 39/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1124e-04 - mae: 0.0187

 51/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1005e-04 - mae: 0.0189

 64/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9818e-04 - mae: 0.0187

 76/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.8392e-04 - mae: 0.0185

 89/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9148e-04 - mae: 0.0187

101/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.8799e-04 - mae: 0.0187

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5.8204e-04 - mae: 0.0186 - val_loss: 5.3901e-04 - val_mae: 0.0183


Epoch 16/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 4.4659e-04 - mae: 0.0164

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.5439e-04 - mae: 0.0177 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.5483e-04 - mae: 0.0180

 39/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.6285e-04 - mae: 0.0180

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.6165e-04 - mae: 0.0182

 64/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.5324e-04 - mae: 0.0180

 77/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.4019e-04 - mae: 0.0179

 90/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.4968e-04 - mae: 0.0181

103/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.4536e-04 - mae: 0.0180

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5.4058e-04 - mae: 0.0180 - val_loss: 4.9915e-04 - val_mae: 0.0176


Epoch 17/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 3.9389e-04 - mae: 0.0153

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.0935e-04 - mae: 0.0170 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.1349e-04 - mae: 0.0174

 39/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.2051e-04 - mae: 0.0173

 50/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.2312e-04 - mae: 0.0175

 63/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.1074e-04 - mae: 0.0174

 76/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.0333e-04 - mae: 0.0173

 89/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.1187e-04 - mae: 0.0175

101/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.0944e-04 - mae: 0.0175

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5.0450e-04 - mae: 0.0174 - val_loss: 4.6422e-04 - val_mae: 0.0168


Epoch 18/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - loss: 3.4300e-04 - mae: 0.0142

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.6425e-04 - mae: 0.0162 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.7873e-04 - mae: 0.0168

 39/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.8366e-04 - mae: 0.0167

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.8421e-04 - mae: 0.0169

 64/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.7974e-04 - mae: 0.0168

 77/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.7041e-04 - mae: 0.0167

 90/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.8026e-04 - mae: 0.0169

103/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.7667e-04 - mae: 0.0169

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4.7282e-04 - mae: 0.0168 - val_loss: 4.3833e-04 - val_mae: 0.0163


Epoch 19/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - loss: 3.0202e-04 - mae: 0.0135

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.2747e-04 - mae: 0.0156 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.4556e-04 - mae: 0.0162

 38/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.5272e-04 - mae: 0.0162

 51/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.5346e-04 - mae: 0.0164

 64/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.5041e-04 - mae: 0.0163

 77/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.4253e-04 - mae: 0.0162

 89/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.5065e-04 - mae: 0.0164

101/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.4860e-04 - mae: 0.0164

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4.4520e-04 - mae: 0.0164 - val_loss: 4.2092e-04 - val_mae: 0.0159


Epoch 20/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - loss: 2.7419e-04 - mae: 0.0133

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.0069e-04 - mae: 0.0152 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.1562e-04 - mae: 0.0156

 41/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.2985e-04 - mae: 0.0158

 55/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.2418e-04 - mae: 0.0159

 69/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.2339e-04 - mae: 0.0158

 82/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.2123e-04 - mae: 0.0159

 95/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.2776e-04 - mae: 0.0160

105/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.2326e-04 - mae: 0.0159

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4.2106e-04 - mae: 0.0159 - val_loss: 4.0654e-04 - val_mae: 0.0156


Epoch 21/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - loss: 2.5510e-04 - mae: 0.0131

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.7638e-04 - mae: 0.0148 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.9241e-04 - mae: 0.0152

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.0585e-04 - mae: 0.0154

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.0070e-04 - mae: 0.0154

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.0176e-04 - mae: 0.0154

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.9783e-04 - mae: 0.0154

 90/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.0488e-04 - mae: 0.0156

102/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.0109e-04 - mae: 0.0155

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3.9939e-04 - mae: 0.0155 - val_loss: 3.8977e-04 - val_mae: 0.0153


Epoch 22/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - loss: 2.3848e-04 - mae: 0.0127

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5343e-04 - mae: 0.0143 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.7435e-04 - mae: 0.0149

 39/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.8069e-04 - mae: 0.0149

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.8241e-04 - mae: 0.0151

 64/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.8311e-04 - mae: 0.0151

 77/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.7886e-04 - mae: 0.0151

 89/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.8338e-04 - mae: 0.0152

101/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.8105e-04 - mae: 0.0152

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3.7957e-04 - mae: 0.0151 - val_loss: 3.7019e-04 - val_mae: 0.0150


Epoch 23/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - loss: 2.2210e-04 - mae: 0.0122

 15/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.4204e-04 - mae: 0.0141 

 28/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5553e-04 - mae: 0.0145

 41/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6758e-04 - mae: 0.0147

 54/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6268e-04 - mae: 0.0147

 67/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6449e-04 - mae: 0.0147

 76/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6271e-04 - mae: 0.0147

 89/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6542e-04 - mae: 0.0148

102/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6279e-04 - mae: 0.0148

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3.6171e-04 - mae: 0.0148 - val_loss: 3.5150e-04 - val_mae: 0.0146


Epoch 24/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - loss: 2.0786e-04 - mae: 0.0116

 15/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.2808e-04 - mae: 0.0139 

 28/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.4106e-04 - mae: 0.0142

 41/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5247e-04 - mae: 0.0144

 54/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.4733e-04 - mae: 0.0144

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5007e-04 - mae: 0.0144

 79/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.4778e-04 - mae: 0.0144

 92/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5012e-04 - mae: 0.0145

105/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.4682e-04 - mae: 0.0144

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3.4585e-04 - mae: 0.0144 - val_loss: 3.3601e-04 - val_mae: 0.0144


Epoch 25/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - loss: 1.9699e-04 - mae: 0.0112

  6/110 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 3.0376e-04 - mae: 0.0135

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.1433e-04 - mae: 0.0136 

 22/110 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.2863e-04 - mae: 0.0139

 32/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.3275e-04 - mae: 0.0140

 42/110 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.3895e-04 - mae: 0.0141

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3560e-04 - mae: 0.0141

 63/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3467e-04 - mae: 0.0141

 73/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3538e-04 - mae: 0.0141

 84/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3510e-04 - mae: 0.0142

 96/110 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3470e-04 - mae: 0.0142

108/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.3180e-04 - mae: 0.0141

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3.3169e-04 - mae: 0.0141 - val_loss: 3.2336e-04 - val_mae: 0.0141


Epoch 26/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - loss: 1.8865e-04 - mae: 0.0109

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0176e-04 - mae: 0.0133 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.1632e-04 - mae: 0.0137

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.2680e-04 - mae: 0.0139

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.2094e-04 - mae: 0.0138

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.2389e-04 - mae: 0.0138

 79/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.2150e-04 - mae: 0.0138

 91/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.2414e-04 - mae: 0.0139

103/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.2000e-04 - mae: 0.0139

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3.1893e-04 - mae: 0.0138 - val_loss: 3.1270e-04 - val_mae: 0.0139


Epoch 27/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - loss: 1.8188e-04 - mae: 0.0108

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8620e-04 - mae: 0.0130 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0446e-04 - mae: 0.0134

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.1503e-04 - mae: 0.0136

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0888e-04 - mae: 0.0136

 68/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.1060e-04 - mae: 0.0135

 81/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0993e-04 - mae: 0.0136

 94/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.1145e-04 - mae: 0.0136

107/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0765e-04 - mae: 0.0136

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3.0745e-04 - mae: 0.0136 - val_loss: 3.0412e-04 - val_mae: 0.0138


Epoch 28/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 1.7710e-04 - mae: 0.0106

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7923e-04 - mae: 0.0128 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.9369e-04 - mae: 0.0131

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0395e-04 - mae: 0.0134

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.9764e-04 - mae: 0.0133

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.9963e-04 - mae: 0.0133

 79/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.9645e-04 - mae: 0.0133

 92/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0068e-04 - mae: 0.0134

105/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.9793e-04 - mae: 0.0133

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.9701e-04 - mae: 0.0133 - val_loss: 2.9772e-04 - val_mae: 0.0136


Epoch 29/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - loss: 1.7484e-04 - mae: 0.0107

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6955e-04 - mae: 0.0126 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8372e-04 - mae: 0.0129

 37/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.9137e-04 - mae: 0.0130

 50/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8989e-04 - mae: 0.0131

 63/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8637e-04 - mae: 0.0130

 76/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8382e-04 - mae: 0.0129

 89/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8978e-04 - mae: 0.0131

101/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8841e-04 - mae: 0.0131

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.8711e-04 - mae: 0.0131 - val_loss: 2.9171e-04 - val_mae: 0.0135


Epoch 30/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - loss: 1.7358e-04 - mae: 0.0107

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5784e-04 - mae: 0.0122 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7352e-04 - mae: 0.0126

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8227e-04 - mae: 0.0129

 54/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7613e-04 - mae: 0.0128

 67/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7622e-04 - mae: 0.0127

 81/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7502e-04 - mae: 0.0127

 95/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.8059e-04 - mae: 0.0129

108/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7773e-04 - mae: 0.0129

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 2.7738e-04 - mae: 0.0129 - val_loss: 2.8308e-04 - val_mae: 0.0133


Epoch 31/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - loss: 1.7004e-04 - mae: 0.0107

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4956e-04 - mae: 0.0120 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6317e-04 - mae: 0.0123

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7083e-04 - mae: 0.0126

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6719e-04 - mae: 0.0125

 64/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6574e-04 - mae: 0.0124

 77/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6194e-04 - mae: 0.0124

 88/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6833e-04 - mae: 0.0126

101/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6964e-04 - mae: 0.0127

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.6792e-04 - mae: 0.0126 - val_loss: 2.7053e-04 - val_mae: 0.0129


Epoch 32/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - loss: 1.6241e-04 - mae: 0.0105

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3706e-04 - mae: 0.0116 

 25/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5221e-04 - mae: 0.0120

 38/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5765e-04 - mae: 0.0122

 50/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5700e-04 - mae: 0.0123

 63/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5430e-04 - mae: 0.0122

 76/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5152e-04 - mae: 0.0121

 89/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6069e-04 - mae: 0.0124

102/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6082e-04 - mae: 0.0124

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.5899e-04 - mae: 0.0124 - val_loss: 2.5537e-04 - val_mae: 0.0125


Epoch 33/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - loss: 1.5165e-04 - mae: 0.0102

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2607e-04 - mae: 0.0113 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4140e-04 - mae: 0.0117

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4834e-04 - mae: 0.0120

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4475e-04 - mae: 0.0120

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4629e-04 - mae: 0.0119

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4248e-04 - mae: 0.0119

 90/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5326e-04 - mae: 0.0122

101/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5265e-04 - mae: 0.0122

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.5067e-04 - mae: 0.0122 - val_loss: 2.4033e-04 - val_mae: 0.0120


Epoch 34/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - loss: 1.4040e-04 - mae: 0.0098

 15/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1962e-04 - mae: 0.0112 

 29/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2777e-04 - mae: 0.0114

 43/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3722e-04 - mae: 0.0117

 57/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3688e-04 - mae: 0.0117

 70/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3613e-04 - mae: 0.0117

 83/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3806e-04 - mae: 0.0118

 96/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4642e-04 - mae: 0.0121

109/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4290e-04 - mae: 0.0120

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 2.4287e-04 - mae: 0.0120 - val_loss: 2.2830e-04 - val_mae: 0.0116


Epoch 35/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - loss: 1.3161e-04 - mae: 0.0094

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0794e-04 - mae: 0.0109 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2272e-04 - mae: 0.0113

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2996e-04 - mae: 0.0115

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2866e-04 - mae: 0.0115

 65/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2915e-04 - mae: 0.0115

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2598e-04 - mae: 0.0115

 90/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3734e-04 - mae: 0.0118

102/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3779e-04 - mae: 0.0119

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.3562e-04 - mae: 0.0118 - val_loss: 2.2048e-04 - val_mae: 0.0113


Epoch 36/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 1.2664e-04 - mae: 0.0092

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9991e-04 - mae: 0.0107 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1529e-04 - mae: 0.0111

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2257e-04 - mae: 0.0114

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2035e-04 - mae: 0.0113

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2256e-04 - mae: 0.0113

 79/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1967e-04 - mae: 0.0113

 91/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3071e-04 - mae: 0.0116

103/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3106e-04 - mae: 0.0117

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.2901e-04 - mae: 0.0116 - val_loss: 2.1555e-04 - val_mae: 0.0111


Epoch 37/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - loss: 1.2421e-04 - mae: 0.0090

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9322e-04 - mae: 0.0105 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0881e-04 - mae: 0.0109

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1581e-04 - mae: 0.0112

 54/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1383e-04 - mae: 0.0111

 67/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1590e-04 - mae: 0.0111

 80/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1477e-04 - mae: 0.0112

 93/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2532e-04 - mae: 0.0115

106/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.2410e-04 - mae: 0.0115

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 2.2288e-04 - mae: 0.0115 - val_loss: 2.1117e-04 - val_mae: 0.0110


Epoch 38/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 10s 94ms/step - loss: 1.2193e-04 - mae: 0.0089

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8764e-04 - mae: 0.0104  

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0288e-04 - mae: 0.0107

 41/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0861e-04 - mae: 0.0110

 54/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0746e-04 - mae: 0.0110

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0995e-04 - mae: 0.0110

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0675e-04 - mae: 0.0109

 91/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1807e-04 - mae: 0.0113

104/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1862e-04 - mae: 0.0113

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.1694e-04 - mae: 0.0113 - val_loss: 2.0573e-04 - val_mae: 0.0108


Epoch 39/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - loss: 1.1804e-04 - mae: 0.0087

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8295e-04 - mae: 0.0102 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9634e-04 - mae: 0.0106

 39/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0122e-04 - mae: 0.0108

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0189e-04 - mae: 0.0108

 65/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0357e-04 - mae: 0.0108

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0096e-04 - mae: 0.0108

 91/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1187e-04 - mae: 0.0111

104/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1252e-04 - mae: 0.0112

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.1112e-04 - mae: 0.0111 - val_loss: 1.9923e-04 - val_mae: 0.0106


Epoch 40/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - loss: 1.1245e-04 - mae: 0.0085

 11/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7923e-04 - mae: 0.0101 

 23/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9255e-04 - mae: 0.0104

 35/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9256e-04 - mae: 0.0105

 47/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9623e-04 - mae: 0.0107

 59/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9683e-04 - mae: 0.0106

 72/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9669e-04 - mae: 0.0106

 84/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9880e-04 - mae: 0.0107

 96/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0650e-04 - mae: 0.0110

109/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0574e-04 - mae: 0.0110

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2.0563e-04 - mae: 0.0110 - val_loss: 1.9306e-04 - val_mae: 0.0104


Epoch 41/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 1.0671e-04 - mae: 0.0085

 15/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7875e-04 - mae: 0.0100 

 29/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8400e-04 - mae: 0.0102

 45/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9094e-04 - mae: 0.0105

 61/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9215e-04 - mae: 0.0105

 75/110 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9010e-04 - mae: 0.0105

 87/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9516e-04 - mae: 0.0107

101/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0092e-04 - mae: 0.0108

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 2.0080e-04 - mae: 0.0108 - val_loss: 1.8876e-04 - val_mae: 0.0103


Epoch 42/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - loss: 1.0257e-04 - mae: 0.0084

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7420e-04 - mae: 0.0099 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8293e-04 - mae: 0.0102

 39/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8568e-04 - mae: 0.0103

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8621e-04 - mae: 0.0104

 65/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8778e-04 - mae: 0.0104

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8624e-04 - mae: 0.0104

 91/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9617e-04 - mae: 0.0107

103/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9682e-04 - mae: 0.0107

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.9669e-04 - mae: 0.0107 - val_loss: 1.8700e-04 - val_mae: 0.0103


Epoch 43/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - loss: 1.0088e-04 - mae: 0.0084

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7282e-04 - mae: 0.0099 

 25/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.8063e-04 - mae: 0.0101

 37/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8257e-04 - mae: 0.0102

 50/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8218e-04 - mae: 0.0102

 62/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8414e-04 - mae: 0.0103

 73/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8331e-04 - mae: 0.0103

 85/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8643e-04 - mae: 0.0104

 97/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9277e-04 - mae: 0.0106

109/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9324e-04 - mae: 0.0106

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.9313e-04 - mae: 0.0106 - val_loss: 1.8753e-04 - val_mae: 0.0103


Epoch 44/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - loss: 1.0139e-04 - mae: 0.0085

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7236e-04 - mae: 0.0099 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7844e-04 - mae: 0.0100

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8081e-04 - mae: 0.0102

 53/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7854e-04 - mae: 0.0101

 66/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8083e-04 - mae: 0.0102

 80/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8111e-04 - mae: 0.0102

 93/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8943e-04 - mae: 0.0105

106/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9021e-04 - mae: 0.0105

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.8990e-04 - mae: 0.0105 - val_loss: 1.8941e-04 - val_mae: 0.0104


Epoch 45/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - loss: 1.0313e-04 - mae: 0.0086

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7228e-04 - mae: 0.0099 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7590e-04 - mae: 0.0100

 39/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7696e-04 - mae: 0.0101

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7618e-04 - mae: 0.0101

 65/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7752e-04 - mae: 0.0101

 78/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7665e-04 - mae: 0.0101

 91/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8571e-04 - mae: 0.0104

103/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8650e-04 - mae: 0.0104

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.8686e-04 - mae: 0.0105 - val_loss: 1.9168e-04 - val_mae: 0.0105


Epoch 46/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 1.0512e-04 - mae: 0.0087

 15/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7189e-04 - mae: 0.0098 

 28/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7247e-04 - mae: 0.0099

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7584e-04 - mae: 0.0101

 51/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7295e-04 - mae: 0.0100

 63/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7400e-04 - mae: 0.0100

 75/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7341e-04 - mae: 0.0100

 87/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7768e-04 - mae: 0.0102

100/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8254e-04 - mae: 0.0103

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.8392e-04 - mae: 0.0104 - val_loss: 1.9378e-04 - val_mae: 0.0106


Epoch 47/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step - loss: 1.0677e-04 - mae: 0.0088

 13/110 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7137e-04 - mae: 0.0099 

 25/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7345e-04 - mae: 0.0099

 38/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7265e-04 - mae: 0.0100

 50/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7031e-04 - mae: 0.0099

 63/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7117e-04 - mae: 0.0099

 75/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7067e-04 - mae: 0.0099

 87/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7482e-04 - mae: 0.0101

 98/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7979e-04 - mae: 0.0103

110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8103e-04 - mae: 0.0103

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.8103e-04 - mae: 0.0103 - val_loss: 1.9549e-04 - val_mae: 0.0107


Epoch 48/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - loss: 1.0791e-04 - mae: 0.0089

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6917e-04 - mae: 0.0098 

 28/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6861e-04 - mae: 0.0098

 42/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7033e-04 - mae: 0.0099

 56/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6880e-04 - mae: 0.0099

 70/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6982e-04 - mae: 0.0099

 83/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7063e-04 - mae: 0.0100

 96/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7700e-04 - mae: 0.0102

109/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7830e-04 - mae: 0.0102

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 1.7818e-04 - mae: 0.0102 - val_loss: 1.9676e-04 - val_mae: 0.0107


Epoch 49/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - loss: 1.0856e-04 - mae: 0.0089

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6790e-04 - mae: 0.0098 

 26/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6839e-04 - mae: 0.0098

 38/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6788e-04 - mae: 0.0099

 50/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6493e-04 - mae: 0.0098

 62/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6657e-04 - mae: 0.0098

 73/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6614e-04 - mae: 0.0098

 85/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6865e-04 - mae: 0.0099

 97/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7438e-04 - mae: 0.0101

109/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7548e-04 - mae: 0.0101

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.7537e-04 - mae: 0.0101 - val_loss: 1.9765e-04 - val_mae: 0.0108


Epoch 50/50


  1/110 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - loss: 1.0884e-04 - mae: 0.0089

 14/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6651e-04 - mae: 0.0098 

 27/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6683e-04 - mae: 0.0098

 40/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6602e-04 - mae: 0.0098

 52/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6266e-04 - mae: 0.0097

 64/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6373e-04 - mae: 0.0097

 76/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6239e-04 - mae: 0.0097

 88/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6810e-04 - mae: 0.0099

100/110 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7093e-04 - mae: 0.0100

110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.7261e-04 - mae: 0.0101 - val_loss: 1.9822e-04 - val_mae: 0.0108


Epoch 50: early stopping


Restoring model weights from the end of the best epoch: 42.


In [6]:
plt.plot(hist.history["loss"], label="train"); plt.plot(hist.history["val_loss"], label="validation"); plt.legend(); plt.title("SimpleRNN loss"); plt.show()
pred_rnn = sc_y.inverse_transform(rnn.predict(X_test, verbose=0)).ravel()
mae_rnn = mean_absolute_error(y_true, pred_rnn)
print(f"SimpleRNN test MAE: {mae_rnn:.1f} MW   (persistence: {baselines.iloc[2]:.1f}, seasonal naive: {baselines.iloc[1]:.1f})")

C:\Users\dww05002\AppData\Local\Temp\ipykernel_28372\1772790273.py:1: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.plot(hist.history["loss"], label="train"); plt.plot(hist.history["val_loss"], label="validation"); plt.legend(); plt.title("SimpleRNN loss"); plt.show()


SimpleRNN test MAE: 47.9 MW   (persistence: 129.0, seasonal naive: 227.1)


In [7]:
i0 = 24*7*28
plt.figure(figsize=(11, 3)); plt.plot(y_true[i0:i0+24*7], label="actual"); plt.plot(pred_rnn[i0:i0+24*7], label="SimpleRNN (1h ahead)")
plt.title("One test week"); plt.ylabel("MW"); plt.legend(); plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_28372\3183717312.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.title("One test week"); plt.ylabel("MW"); plt.legend(); plt.show()


🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 10B — Multivariate RNN Pt 2: the LSTM swap, stacking, and a classification head
- One-word swap: SimpleRNN -> LSTM. Params x4: (8+30)*30+30 = 1,170 -> 4,680. Read it off summary().
- Stacked: return_sequences=True keeps the (24, 30) sequence for the second layer. More capacity is not automatically better - read the table.
- Bake-off table: persistence 129, seasonal naive 227, SimpleRNN ~48, LSTM ~43, stacked ~67 (worse - more capacity is not automatically better). The number to say: how much value over the dummy.
- Classification head on the SAME tensors: is this a peak hour (top 10% of training demand)? sigmoid + binary_crossentropy; majority baseline 90% so read precision/recall.
- Save -> load_model -> identical predictions. Reproducibility is a seed AND a saved artifact.
-->


## The LSTM swap, and a stacked RNN

In [8]:
lstm = Sequential([LSTM(30, input_shape=(n_steps, n_features)), Dense(1)])
lstm.compile(optimizer="adam", loss="mse", metrics=["mae"])
lstm.summary()
lstm.fit(X_train, y_train, epochs=50, batch_size=64, validation_split=0.2, callbacks=[es], verbose=0)
pred_lstm = sc_y.inverse_transform(lstm.predict(X_test, verbose=0)).ravel()
mae_lstm = mean_absolute_error(y_true, pred_lstm)
print(f"LSTM test MAE: {mae_lstm:.1f} MW   (persistence: {baselines.iloc[2]:.1f}, seasonal naive: {baselines.iloc[1]:.1f})")

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30)             │         4,680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,711 (18.40 KB)

 Trainable params: 4,711 (18.40 KB)

 Non-trainable params: 0 (0.00 B)

Restoring model weights from the end of the best epoch: 50.


LSTM test MAE: 43.2 MW   (persistence: 129.0, seasonal naive: 227.1)


In [9]:
stacked = Sequential([SimpleRNN(30, return_sequences=True, input_shape=(n_steps, n_features)),   # hands the whole (24, 30) sequence down
                      SimpleRNN(30),
                      Dense(1)])
stacked.compile(optimizer="adam", loss="mse", metrics=["mae"])
stacked.summary()
stacked.fit(X_train, y_train, epochs=50, batch_size=64, validation_split=0.2, callbacks=[es], verbose=0)
pred_stacked = sc_y.inverse_transform(stacked.predict(X_test, verbose=0)).ravel()
mae_stacked = mean_absolute_error(y_true, pred_stacked)
print(f"stacked SimpleRNN test MAE: {mae_stacked:.1f} MW   (persistence: {baselines.iloc[2]:.1f}, seasonal naive: {baselines.iloc[1]:.1f})")

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 24, 30)         │         1,170 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,031 (11.84 KB)

 Trainable params: 3,031 (11.84 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 27: early stopping


Restoring model weights from the end of the best epoch: 19.


stacked SimpleRNN test MAE: 67.1 MW   (persistence: 129.0, seasonal naive: 227.1)


In [10]:
pd.Series({"mean-only": baselines.iloc[0], "seasonal naive": baselines.iloc[1], "persistence": baselines.iloc[2],
           "SimpleRNN": mae_rnn, "LSTM": mae_lstm, "stacked SimpleRNN": mae_stacked}, name="test MAE, 1h ahead (MW)").round(1)

mean-only            563.3
seasonal naive       227.1
persistence          129.0
SimpleRNN             47.9
LSTM                  43.2
stacked SimpleRNN     67.1
Name: test MAE, 1h ahead (MW), dtype: float64

## Same tensors, a classification head: is this a peak hour?

Define a peak as the **top 10% of training-set demand**. Change the head to `sigmoid`, the loss to `binary_crossentropy`, and read precision/recall - the majority-class baseline is 90%, so accuracy tells you nothing.

In [11]:
thr = train["Demand"].quantile(0.90)
peak_train = (sc_y.inverse_transform(y_train.reshape(-1, 1)).ravel() > thr).astype(int)
peak_test  = (y_true > thr).astype(int)
print(f"peak threshold: {thr:.0f} MW | peak share in test: {peak_test.mean():.1%}")

clf = Sequential([LSTM(30, input_shape=(n_steps, n_features)), Dense(1, activation="sigmoid")])
clf.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
clf.fit(X_train, peak_train, epochs=50, batch_size=64, validation_split=0.2, callbacks=[es], verbose=0)
p = (clf.predict(X_test, verbose=0).ravel() > 0.5).astype(int)
print(classification_report(peak_test, p, target_names=["normal hour", "PEAK hour"]))
print(confusion_matrix(peak_test, p))

peak threshold: 4313 MW | peak share in test: 7.4%


C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 24: early stopping


Restoring model weights from the end of the best epoch: 16.


              precision    recall  f1-score   support

 normal hour       0.99      0.99      0.99      8089
   PEAK hour       0.89      0.83      0.86       647

    accuracy                           0.98      8736
   macro avg       0.94      0.91      0.92      8736
weighted avg       0.98      0.98      0.98      8736

[[8024   65]
 [ 110  537]]


## Save the model and use it again

In [12]:
lstm.save('E2_Multivariate_Demand_RNN.keras')
reloaded = load_model('E2_Multivariate_Demand_RNN.keras')
print("reloaded model reproduces the predictions:", np.allclose(lstm.predict(X_test[:5], verbose=0), reloaded.predict(X_test[:5], verbose=0)))

reloaded model reproduces the predictions: True


## On your own

- Change `n_steps` to 6, then 168. Which look-back wins for one hour ahead? For the peak-hour flag?
- Add `Dropout(0.2)` after the recurrent layer. Does it help a model that is already close to persistence?
- Swap `LSTM` for `GRU` - count the parameters before you run it (G=3).